
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db-[kuerzel]
spec:
  instances: 1 # cluster mit 1 instanz. Bei mehreren Inszanzen werden daten repliziert
  enablePDB: false # Muss bei nur einer Instanz deaktiviert sein. -> Für Zero Downtime Updates
  bootstrap: # erstellt eine neue datenbank app mit dem owner app
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: immich-db-configmap-[kuerzel]
          key: init-db.sql   
  imageCatalogRef: # Image catalog verwenden ansonsten wird einfach die latest installiert
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage: # azure storage
    size: 1Gi # 1Gigabyte sollte genügen.
    storageClass: managed-csi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db-configmap-[kuerzel]
data:
  init-db.sql: |
    CREATE EXTENSION IF NOT EXISTS vector CASCADE;
    CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis-[kuerzel]
spec:
  selector:
    matchLabels:
      app: immich-redis-[kuerzel]
  template:
    metadata:
      labels:
        app: immich-redis-[kuerzel]
    spec:
      containers:
      - name: immich-redis-[kuerzel]
        image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
        ports:
        - containerPort: 6379
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:  
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: immich-redis-[kuerzel]-svc
spec:
  selector:
    app: immich-redis-[kuerzel]
  ports:
  - port: 6379
    targetPort: 6379


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning-[kuerzel]
spec:
  selector:
    matchLabels:
      app: immich-machine-learning-[kuerzel]
  template:
    metadata:
      labels:
        app: immich-machine-learning-[kuerzel]
    spec:
      containers:
      - name: immich-machine-learning-[kuerzel]
        image: ghcr.io/immich-app/immich-machine-learning:v2.2.0
        envFrom:
        - configMapRef:
            name: immich-machine-learning-config-[kuerzel]
        ports:
        - containerPort: 3003
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:    
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /cache
          name: cache
      volumes:
        - emptyDir: {}
          name: cache

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-machine-learning-config-[kuerzel]
data:
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning-[kuerzel]:3003
  REDIS_HOSTNAME: immich-redis-[kuerzel]-svc
  TRANSFORMERS_CACHE: /cache

---

apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning-[kuerzel]
spec:
  selector:
    app: immich-machine-learning-[kuerzel]
  ports:
  - port: 3003
    targetPort: 3003


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server-[kuerzel]
spec:
  selector:
    matchLabels:
      app: immich-server-[kuerzel]
  template:
    metadata:
      labels:
        app: immich-server-[kuerzel]
    spec:
      containers:
      - name: immich-server-[kuerzel]
        image: ghcr.io/immich-app/immich-server:v2.2.0
        envFrom:
        - configMapRef:
            name: immich-server-config-[kuerzel]
        env:
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-db-[kuerzel]-app
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-db-[kuerzel]-app
              key: password  
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-db-[kuerzel]-app
              key: user  
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: immich-db-[kuerzel]-app
              key: dbname                
        ports:
        - containerPort: 2283
        volumeMounts:
        - mountPath: /data
          name: data        
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-server-[kuerzel]-pvc
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server-[kuerzel]-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteOnce


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-server-config-[kuerzel]
data:
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning-[kuerzel]:3003
  REDIS_HOSTNAME: immich-redis-[kuerzel]-svc
  TZ: /Europe/Zurich
  UPLOAD_LOCATION: ./library

---

apiVersion: v1
kind: Service
metadata:
  name: immich-server-[kuerzel]-svc
spec:
  selector:
    app: immich-server-[kuerzel]
  ports:
  - port: 2283
    targetPort: 2283

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-[kuerzel]-ingressroute
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-dev02.egeli-apps.dev # Hier ist die Domain (oder Traefik IP direkt) einzugeben, für die der DNS A Rekord von oben erstellt wurde
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich-[kuerzel].traefik-dev02.egeli-apps.dev`)
      kind: Rule
      services:
        - name: immich-server-[kuerzel]-svc
          port: 2283
  tls:
    secretName: traefik-dev02-immich-[kuerzel]

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dev02-immich-[kuerzel]
spec:
  secretName: traefik-dev02-immich-[kuerzel]
  # Wenn beim Deployment mehrere Domains benötigt werden, können diese hier einfach eingefügt werden, sodass nicht jedes Mal mehrere Zertifikate erstellt werden müssen
  dnsNames:
    - immich-[kuerzel].traefik-dev02.egeli-apps.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

--- 


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
